---
 - name: Default playbook
   become: yes
   hosts: default
   gather_facts: yes
   vars:
     ubuntu_hardening_extra_users:
       - "packer"
   roles:
      - ansible-role-pcp
      - ansible-role-ubuntu-hardening

   vars:
     build-id: "{{ lookup('env','TRAVIS_BUILD_ID') }}"

   tasks:
     - name: Create neoway release file
        copy:
        dest: "/etc/neoway-release"
        content: |
          neoway-base-image
          build-id:"{{ build-id }}"