---
 - name: Default playbook
   become: yes
   hosts: default
   gather_facts: yes
   vars:
     ubuntu_hardening_extra_users:
       - "packer"

   roles:
      - ansible-role-ubuntu-hardening

   tasks:
     - name: Create neoway release file
       copy:
         dest: /etc/neoway-release
         content: "neoway-base-image\nbuild-id:\"{{ lookup('env','TRAVIS_BUILD_ID') }}\"\n"
